"""Declarative base for all ORM models.

Alembic imports this module to discover metadata for autogenerated migrations,
so every model module must ultimately be imported from here.
"""

from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Base class for DevPilot ORM models."""
